"use client";

import { AppHeader } from "@/components/app-header";
import { BellRing,CheckCircle2,LoaderCircle,Mail,ShieldCheck } from "lucide-react";
import { useEffect,useState } from "react";

type Pref={marketing_opt_in:boolean;study_reminders:boolean;transactional_enabled:boolean;unsubscribed_at:string|null;consent_version:string|null};

export default function CommunicationPreferencesPage(){
 const [pref,setPref]=useState<Pref|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 useEffect(()=>{void load();},[]);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/account/communication-preferences",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setPref(d.preferences);}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar suas preferências.");}finally{setLoading(false);}}
 async function save(){if(!pref)return;setSaving(true);setSaved(false);setError("");try{const r=await fetch("/api/account/communication-preferences",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({marketing_opt_in:pref.marketing_opt_in,study_reminders:pref.study_reminders})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSaved(true);await load();}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar suas preferências.");}finally{setSaving(false);}}
 return <main className="app-surface"><AppHeader/><div className="practice-shell" style={{maxWidth:850}}><section className="result-card" style={{textAlign:"left"}}><span className="result-kicker">COMUNICAÇÕES</span><h1>Preferências de e-mail</h1><p>Escolha quais comunicações opcionais deseja receber. Mensagens transacionais necessárias para sua conta continuam habilitadas.</p>{loading?<div><LoaderCircle className="spin"/><p>Carregando preferências...</p></div>:error&&!pref?<p className="form-error">{error}</p>:pref&&<div style={{display:"grid",gap:14,marginTop:22}}><label style={{display:"flex",gap:12,alignItems:"center",padding:16,border:"1px solid #ddd8ce"}}><input type="checkbox" checked={pref.marketing_opt_in} onChange={e=>{setSaved(false);setPref({...pref,marketing_opt_in:e.target.checked});}}/><Mail/><span><b>Novidades e conteúdos</b><small style={{display:"block"}}>Atualizações do Domina OAB, materiais e novidades.</small></span></label><label style={{display:"flex",gap:12,alignItems:"center",padding:16,border:"1px solid #ddd8ce"}}><input type="checkbox" checked={pref.study_reminders} onChange={e=>{setSaved(false);setPref({...pref,study_reminders:e.target.checked});}}/><BellRing/><span><b>Lembretes de estudo</b><small style={{display:"block"}}>Avisos para manter sua rotina de preparação.</small></span></label><div style={{display:"flex",gap:10,alignItems:"center",paddingTop:8}}><button className="button" disabled={saving} onClick={()=>void save()}>{saving?<LoaderCircle className="spin" size={16}/>:<CheckCircle2 size={16}/>}Salvar preferências</button><button disabled={saving||(!pref.marketing_opt_in&&!pref.study_reminders)} onClick={()=>{setPref({...pref,marketing_opt_in:false,study_reminders:false});setSaved(false);}}>Cancelar comunicações opcionais</button></div>{saved&&<p><CheckCircle2 size={15}/> Preferências atualizadas.</p>}{error&&<p className="form-error">{error}</p>}<div style={{display:"flex",gap:9,alignItems:"start",marginTop:12,padding:14,background:"#f7f5f0"}}><ShieldCheck size={17}/><small>Comunicações transacionais sobre conta, acesso ou pagamento não dependem do consentimento de marketing.</small></div></div>}</section></div></main>;
}
