"use client";

import { useEffect,useState } from "react";
import { Archive,CheckCircle2,Copy,Edit3,Eye,FileClock,FilePlus2,LoaderCircle,PauseCircle,Search,Upload } from "lucide-react";

type Status="draft"|"reviewing"|"published"|"suspended"|"archived";
type Difficulty="easy"|"medium"|"hard";
type Incidence="low"|"medium"|"high";
type Version={version_no:number;status:Status;change_type:string;changed_by_email:string|null;created_at:string;statement:string;exam_name:string|null;exam_edition:string|null;exam_phase:string|null;subtopic:string|null;incidence:Incidence|null};
type Q={id:number;code:string;discipline_slug:string;discipline:string;topic:string|null;subtopic:string|null;statement:string;options:string[];correct_index:number;explanation:string;source_label:string|null;difficulty:Difficulty;incidence:Incidence|null;status:Status;exam_name:string|null;exam_edition:string|null;exam_phase:string|null;open_reports:number;version_count:number;last_edited_by_email:string|null};
const blank={id:null as number|null,code:"",discipline_slug:"etica-profissional",topic:"",subtopic:"",statement:"",options:["","","",""],correct_index:0,explanation:"",source_label:"",difficulty:"medium" as Difficulty,incidence:"medium" as Incidence,status:"draft" as Status,exam_name:"OAB",exam_edition:"",exam_phase:"1ª fase"};

export function AdminQuestions(){
 const [items,setItems]=useState<Q[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[form,setForm]=useState(blank),[history,setHistory]=useState<Record<number,Version[]>>({});
 async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/admin/questions?q=${encodeURIComponent(query)}&status=${encodeURIComponent(status)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.questions||[]);}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar questões.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/admin/questions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);setForm(blank);await load();}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar questão.");}finally{setBusy(false);}}
 async function setQuestionStatus(id:number,next:Status){setBusy(true);setError("");try{const r=await fetch("/api/admin/questions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status:next})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:"Erro ao atualizar questão.");}finally{setBusy(false);}}
 async function duplicate(id:number){setBusy(true);try{const r=await fetch("/api/admin/questions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"duplicate",id})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:"Erro ao duplicar questão.");}finally{setBusy(false);}}
 async function importBatch(){const raw=window.prompt("Cole um array JSON de questões. Máximo: 500 itens.","[");if(!raw)return;setBusy(true);setError("");try{const importedItems=JSON.parse(raw);if(!Array.isArray(importedItems))throw new Error("O conteúdo precisa ser um array JSON.");const r=await fetch("/api/admin/questions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"import",items:importedItems})});const d=await r.json();if(!r.ok)throw new Error(d.error);window.alert(`Importadas: ${d.imported??0}. Falhas: ${d.failed??0}.`);await load();}catch(e){setError(e instanceof Error?e.message:"Erro na importação.");}finally{setBusy(false);}}
 async function showHistory(id:number){if(history[id]){setHistory(current=>{const next={...current};delete next[id];return next;});return;}try{const r=await fetch(`/api/admin/questions?history_id=${id}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setHistory(current=>({...current,[id]:d.versions||[]}));}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar histórico.");}}
 function edit(q:Q){setForm({id:q.id,code:q.code,discipline_slug:q.discipline_slug,topic:q.topic||"",subtopic:q.subtopic||"",statement:q.statement,options:q.options,correct_index:q.correct_index,explanation:q.explanation,source_label:q.source_label||"",difficulty:q.difficulty,incidence:q.incidence||"medium",status:q.status,exam_name:q.exam_name||"OAB",exam_edition:q.exam_edition||"",exam_phase:q.exam_phase||"1ª fase"});window.scrollTo({top:0,behavior:"smooth"});}
 return <div style={{display:"grid",gap:24}}>
  <section className="admin-panel"><header><div><span><FilePlus2/> CONTEÚDO</span><h2>{form.id?"Editar questão":"Nova questão"}</h2></div><div style={{display:"flex",gap:8}}><button type="button" onClick={()=>void importBatch()} disabled={busy}><Upload size={15}/>Importar lote</button><small>4 ALTERNATIVAS</small></div></header>
   <form onSubmit={save} style={{display:"grid",gap:12}}>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:10}}>
     <input required placeholder="Código ex. ETICA-001" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/>
     <input required placeholder="Disciplina (slug)" value={form.discipline_slug} onChange={e=>setForm({...form,discipline_slug:e.target.value})}/>
     <input placeholder="Exame" value={form.exam_name} onChange={e=>setForm({...form,exam_name:e.target.value})}/>
     <input placeholder="Edição ex. 44º Exame" value={form.exam_edition} onChange={e=>setForm({...form,exam_edition:e.target.value})}/>
     <input placeholder="Fase ex. 1ª fase" value={form.exam_phase} onChange={e=>setForm({...form,exam_phase:e.target.value})}/>
    </div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:10}}>
     <input required placeholder="Tema" value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/>
     <input placeholder="Subtema" value={form.subtopic} onChange={e=>setForm({...form,subtopic:e.target.value})}/>
     <select value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value as Difficulty})}><option value="easy">Fácil</option><option value="medium">Média</option><option value="hard">Difícil</option></select>
     <select value={form.incidence} onChange={e=>setForm({...form,incidence:e.target.value as Incidence})}><option value="low">Baixa incidência</option><option value="medium">Média incidência</option><option value="high">Alta incidência</option></select>
    </div>
    <textarea required rows={3} placeholder="Enunciado" value={form.statement} onChange={e=>setForm({...form,statement:e.target.value})}/>
    {form.options.map((o,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"44px 1fr",gap:8,alignItems:"center"}}><label style={{fontWeight:800}}><input type="radio" name="correct" checked={form.correct_index===i} onChange={()=>setForm({...form,correct_index:i})}/> {String.fromCharCode(65+i)}</label><input required placeholder={`Alternativa ${String.fromCharCode(65+i)}`} value={o} onChange={e=>{const options=[...form.options];options[i]=e.target.value;setForm({...form,options});}}/></div>)}
    <textarea required rows={3} placeholder="Explicação / fundamentação legal" value={form.explanation} onChange={e=>setForm({...form,explanation:e.target.value})}/>
    <div style={{display:"grid",gridTemplateColumns:"1fr 200px",gap:10}}><input placeholder="Fonte / referência" value={form.source_label} onChange={e=>setForm({...form,source_label:e.target.value})}/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})}><option value="draft">Rascunho</option><option value="reviewing">Em revisão</option><option value="published">Publicada</option><option value="suspended">Suspensa</option><option value="archived">Arquivada</option></select></div>
    <div style={{display:"flex",gap:8}}><button className="button" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:<CheckCircle2 size={16}/>}Salvar questão</button>{form.id&&<button type="button" onClick={()=>setForm(blank)}>Cancelar edição</button>}</div>
   </form>
  </section>
  <section className="admin-panel"><header><div><span><Search/> BANCO</span><h2>Questões cadastradas</h2></div><small>{items.length} RESULTADOS</small></header>
   <form onSubmit={e=>{e.preventDefault();void load();}} style={{display:"flex",gap:8,marginBottom:18,flexWrap:"wrap"}}><input style={{flex:1,minWidth:260}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar código, tema, subtema, edição ou enunciado"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="draft">Rascunhos</option><option value="reviewing">Em revisão</option><option value="published">Publicadas</option><option value="suspended">Suspensas</option><option value="archived">Arquivadas</option></select><button className="button"><Search size={16}/>Buscar</button></form>
   {error&&<p className="form-error">{error}</p>}{loading?<div className="admin-empty"><p>Carregando...</p></div>:<div style={{display:"grid",gap:10}}>{items.map(q=><article key={q.id} style={{border:"1px solid #e2ddd3",padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:18,flexWrap:"wrap"}}><div style={{flex:1,minWidth:280}}><small>{q.code} · {q.discipline} · {q.topic||"Sem tema"}{q.subtopic?` / ${q.subtopic}`:""}{q.exam_edition?` · ${q.exam_edition}`:""}</small><h3 style={{margin:"6px 0"}}>{q.statement}</h3><p style={{margin:0,fontSize:12}}>{q.open_reports} reporte(s) aberto(s) · {statusLabel(q.status)} · dificuldade {difficultyLabel(q.difficulty)} · incidência {incidenceLabel(q.incidence||"medium")} · {q.version_count||0} versão(ões){q.last_edited_by_email?` · última edição: ${q.last_edited_by_email}`:""}</p></div><div style={{display:"flex",gap:7,alignItems:"start",flexWrap:"wrap"}}><button onClick={()=>edit(q)}><Edit3 size={15}/> Editar</button><button onClick={()=>void duplicate(q.id)}><Copy size={15}/> Duplicar</button><button onClick={()=>void showHistory(q.id)}><FileClock size={15}/> Histórico</button>{q.status==="draft"&&<button onClick={()=>void setQuestionStatus(q.id,"reviewing")}><Eye size={15}/> Enviar à revisão</button>}{q.status!=="published"&&<button onClick={()=>void setQuestionStatus(q.id,"published")}><CheckCircle2 size={15}/> Publicar</button>}{q.status==="published"&&<button onClick={()=>void setQuestionStatus(q.id,"suspended")}><PauseCircle size={15}/> Suspender</button>}{q.status!=="archived"&&<button onClick={()=>void setQuestionStatus(q.id,"archived")}><Archive size={15}/> Arquivar</button>}</div></div>{history[q.id]&&<div style={{marginTop:12,paddingTop:12,borderTop:"1px solid #eee8df"}}><b style={{fontSize:12}}>Histórico de versões</b>{history[q.id].length===0?<p style={{fontSize:11}}>Nenhuma versão anterior registrada.</p>:history[q.id].map(v=><p key={v.version_no} style={{fontSize:11,margin:"6px 0"}}>v{v.version_no} · {statusLabel(v.status)} · {v.change_type==="status_change"?"mudança de status":"edição de conteúdo"} · {new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v.created_at))}{v.exam_edition?` · ${v.exam_edition}`:""}{v.changed_by_email?` · ${v.changed_by_email}`:""}</p>)}</div>}</article>)}</div>}
  </section>
 </div>;
}
function statusLabel(v:Status){return ({draft:"Rascunho",reviewing:"Em revisão",published:"Publicada",suspended:"Suspensa",archived:"Arquivada"} as const)[v]}
function difficultyLabel(v:Difficulty){return ({easy:"fácil",medium:"média",hard:"difícil"} as const)[v]}
function incidenceLabel(v:Incidence){return ({low:"baixa",medium:"média",high:"alta"} as const)[v]}
