-- Domina OAB - Fase 2: tentativas e respostas de simulados

create table if not exists public.simulation_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  discipline_id bigint not null references public.disciplines(id),
  status text not null default 'started' check (status in ('started','completed','abandoned')),
  total_questions integer not null default 0,
  answered_questions integer not null default 0,
  correct_answers integer not null default 0,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.simulation_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.simulation_attempts(id) on delete cascade,
  question_id bigint not null references public.questions(id),
  selected_index integer not null check (selected_index between 0 and 3),
  correct boolean not null,
  answered_at timestamptz not null default now(),
  unique(attempt_id,question_id)
);

create index if not exists simulation_attempts_user_started_idx on public.simulation_attempts(user_id,started_at desc);
create index if not exists simulation_answers_attempt_idx on public.simulation_answers(attempt_id);

alter table public.simulation_attempts enable row level security;
alter table public.simulation_answers enable row level security;

create or replace function public.start_simulation(p_user_id uuid,p_discipline_slug text,p_total_questions integer)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_discipline bigint; v_id bigint;
begin
  if p_user_id is null then raise exception 'invalid_user'; end if;
  if not exists(select 1 from public.user_profiles where user_id=p_user_id and account_status='active') then raise exception 'inactive_user'; end if;
  select id into v_discipline from public.disciplines where slug=p_discipline_slug and active=true;
  if v_discipline is null then raise exception 'discipline_not_found'; end if;
  update public.simulation_attempts set status='abandoned',updated_at=now() where user_id=p_user_id and discipline_id=v_discipline and status='started';
  insert into public.simulation_attempts(user_id,discipline_id,total_questions) values(p_user_id,v_discipline,greatest(0,p_total_questions)) returning id into v_id;
  return jsonb_build_object('attempt_id',v_id);
end;
$$;

create or replace function public.record_simulation_answer(p_user_id uuid,p_attempt_id bigint,p_question_id bigint,p_selected_index integer)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_correct_index integer; v_correct boolean; v_owner uuid;
begin
  select user_id into v_owner from public.simulation_attempts where id=p_attempt_id and status='started';
  if v_owner is null or v_owner<>p_user_id then raise exception 'attempt_not_found'; end if;
  select correct_index into v_correct_index from public.questions where id=p_question_id and status='published';
  if v_correct_index is null then raise exception 'question_not_found'; end if;
  if p_selected_index not between 0 and 3 then raise exception 'invalid_option'; end if;
  v_correct:=p_selected_index=v_correct_index;
  insert into public.simulation_answers(attempt_id,question_id,selected_index,correct)
  values(p_attempt_id,p_question_id,p_selected_index,v_correct)
  on conflict(attempt_id,question_id) do update set selected_index=excluded.selected_index,correct=excluded.correct,answered_at=now();
  update public.simulation_attempts a set
    answered_questions=(select count(*)::int from public.simulation_answers where attempt_id=a.id),
    correct_answers=(select count(*)::int from public.simulation_answers where attempt_id=a.id and correct=true),
    updated_at=now()
  where a.id=p_attempt_id;
  return jsonb_build_object('correct',v_correct,'correct_index',v_correct_index);
end;
$$;

create or replace function public.finish_simulation(p_user_id uuid,p_attempt_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v public.simulation_attempts%rowtype;
begin
  update public.simulation_attempts set status='completed',completed_at=now(),updated_at=now()
  where id=p_attempt_id and user_id=p_user_id and status='started' returning * into v;
  if not found then raise exception 'attempt_not_found'; end if;
  return jsonb_build_object('attempt_id',v.id,'answered',v.answered_questions,'correct',v.correct_answers,'total',v.total_questions,'score_percent',case when v.total_questions>0 then round(v.correct_answers::numeric/v.total_questions*100)::int else 0 end);
end;
$$;

create or replace function public.admin_simulations()
returns jsonb
language sql
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'total30',(select count(*)::int from public.simulation_attempts where started_at>=now()-interval '30 days'),
    'completed30',(select count(*)::int from public.simulation_attempts where status='completed' and started_at>=now()-interval '30 days'),
    'averageScore',coalesce((select round(avg(correct_answers::numeric/nullif(total_questions,0)*100))::int from public.simulation_attempts where status='completed' and total_questions>0 and started_at>=now()-interval '30 days'),0),
    'recent',coalesce((select jsonb_agg(to_jsonb(x)) from (
      select a.id,p.full_name,p.email,d.name discipline,a.status,a.total_questions,a.answered_questions,a.correct_answers,a.started_at,a.completed_at
      from public.simulation_attempts a join public.user_profiles p on p.user_id=a.user_id join public.disciplines d on d.id=a.discipline_id
      order by a.started_at desc limit 100
    ) x),'[]'::jsonb),
    'hardestQuestions',coalesce((select jsonb_agg(to_jsonb(x)) from (
      select q.id,q.code,q.statement,t.name topic,count(sa.id)::int answers,count(sa.id) filter(where sa.correct=false)::int errors,
        round((count(sa.id) filter(where sa.correct=false)::numeric/nullif(count(sa.id),0))*100)::int error_rate
      from public.simulation_answers sa join public.questions q on q.id=sa.question_id left join public.question_topics t on t.id=q.topic_id
      group by q.id,q.code,q.statement,t.name having count(sa.id)>=1 order by error_rate desc,answers desc limit 20
    ) x),'[]'::jsonb)
  );
$$;

revoke all on function public.start_simulation(uuid,text,integer) from public,anon,authenticated;
revoke all on function public.record_simulation_answer(uuid,bigint,bigint,integer) from public,anon,authenticated;
revoke all on function public.finish_simulation(uuid,bigint) from public,anon,authenticated;
revoke all on function public.admin_simulations() from public,anon,authenticated;
grant execute on function public.start_simulation(uuid,text,integer) to service_role;
grant execute on function public.record_simulation_answer(uuid,bigint,bigint,integer) to service_role;
grant execute on function public.finish_simulation(uuid,bigint) to service_role;
grant execute on function public.admin_simulations() to service_role;
