-- Domina OAB: estrutura inicial Supabase/PostgreSQL
-- Execute no SQL Editor do projeto Domina OAB.

create table if not exists public.pilot_leads (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'founder' check (status = 'founder'),
  consent_version text not null default '2026-09',
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view','simulado_started','simulado_completed')),
  path text not null default '/',
  session_id text not null,
  referrer text not null default '',
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_type_created_idx
  on public.analytics_events(event_type, created_at);
create index if not exists analytics_events_session_idx
  on public.analytics_events(session_id);

create table if not exists public.plans (
  id text primary key,
  slug text not null unique,
  name text not null,
  billing_type text not null check (billing_type in ('recurring','one_time','promotional')),
  duration_days integer,
  price_cents integer not null check (price_cents >= 0),
  max_installments integer not null default 1 check (max_installments >= 1),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  plan_id text not null references public.plans(id),
  provider text not null default 'mercado_pago',
  provider_subscription_id text unique,
  status text not null default 'pending',
  starts_at timestamptz,
  current_period_end timestamptz,
  next_charge_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_user_status_idx
  on public.subscriptions(user_id, status);
create index if not exists subscriptions_email_idx
  on public.subscriptions(email);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  plan_id text not null references public.plans(id),
  subscription_id bigint references public.subscriptions(id) on delete set null,
  provider text not null default 'mercado_pago',
  provider_payment_id text unique,
  status text not null default 'pending',
  payment_method text,
  installments integer not null default 1,
  gross_amount_cents integer not null,
  fee_amount_cents integer not null default 0,
  net_amount_cents integer not null default 0,
  approved_at timestamptz,
  available_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payments_status_created_idx
  on public.payments(status, created_at);
create index if not exists payments_user_idx
  on public.payments(user_id);

create table if not exists public.entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  plan_id text not null references public.plans(id),
  source_type text not null,
  source_id text,
  status text not null default 'pending',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists entitlements_user_status_idx
  on public.entitlements(user_id, status);
create index if not exists entitlements_email_idx
  on public.entitlements(email);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  provider text not null default 'mercado_pago',
  provider_event_id text not null unique,
  event_type text not null,
  resource_id text,
  processing_status text not null default 'received',
  payload text not null,
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists payment_events_status_received_idx
  on public.payment_events(processing_status, received_at);

insert into public.plans (id,slug,name,billing_type,duration_days,price_cents,max_installments,active)
values
  ('domina-monthly','domina-monthly','Domina Mensal','recurring',30,4990,1,true),
  ('domina-90','domina-90','Domina 90 dias','one_time',90,12990,1,true),
  ('domina-annual','domina-annual','Domina Anual','one_time',365,36000,12,true),
  ('founder-annual','founder-annual','Acesso Fundador','promotional',365,0,1,true)
on conflict (id) do update set
  slug=excluded.slug,
  name=excluded.name,
  billing_type=excluded.billing_type,
  duration_days=excluded.duration_days,
  price_cents=excluded.price_cents,
  max_installments=excluded.max_installments,
  active=excluded.active,
  updated_at=now();

alter table public.pilot_leads enable row level security;
alter table public.analytics_events enable row level security;
alter table public.plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.payments enable row level security;
alter table public.entitlements enable row level security;
alter table public.payment_events enable row level security;

create or replace function public.founder_availability()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'remaining', greatest(0, 25 - count(*)),
    'limit', 25
  )
  from public.pilot_leads
  where status = 'founder';
$$;

create or replace function public.register_founder(
  p_email text,
  p_consent_version text default '2026-09'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(trim(p_email));
  v_total integer;
  v_inserted boolean := false;
begin
  if v_email = '' or length(v_email) > 254 then
    raise exception 'invalid_email';
  end if;

  lock table public.pilot_leads in share row exclusive mode;

  if exists (select 1 from public.pilot_leads where email = v_email) then
    select count(*) into v_total
    from public.pilot_leads
    where status = 'founder';

    return jsonb_build_object(
      'status','founder',
      'remaining',greatest(0,25-v_total),
      'inserted',false
    );
  end if;

  select count(*) into v_total
  from public.pilot_leads
  where status = 'founder';

  if v_total >= 25 then
    return jsonb_build_object(
      'closed',true,
      'remaining',0,
      'error','As vagas gratuitas foram preenchidas.'
    );
  end if;

  insert into public.pilot_leads(email,status,consent_version)
  values (
    v_email,
    'founder',
    coalesce(nullif(p_consent_version,''),'2026-09')
  );

  v_inserted := true;

  select count(*) into v_total
  from public.pilot_leads
  where status = 'founder';

  return jsonb_build_object(
    'status','founder',
    'remaining',greatest(0,25-v_total),
    'inserted',v_inserted
  );
end;
$$;

create or replace function public.record_analytics(
  p_event_type text,
  p_path text,
  p_session_id text,
  p_referrer text default '',
  p_utm_source text default '',
  p_utm_medium text default '',
  p_utm_campaign text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_event_type not in ('page_view','simulado_started','simulado_completed') then
    raise exception 'invalid_event';
  end if;

  if coalesce(trim(p_session_id),'') = '' then
    raise exception 'invalid_session';
  end if;

  insert into public.analytics_events(
    event_type,path,session_id,referrer,utm_source,utm_medium,utm_campaign
  )
  values (
    left(p_event_type,40),
    left(coalesce(nullif(p_path,''),'/'),300),
    left(p_session_id,80),
    left(coalesce(p_referrer,''),500),
    left(coalesce(p_utm_source,''),120),
    left(coalesce(p_utm_medium,''),120),
    left(coalesce(p_utm_campaign,''),160)
  );
end;
$$;

grant execute on function public.founder_availability() to anon, authenticated;
grant execute on function public.register_founder(text,text) to anon, authenticated;
grant execute on function public.record_analytics(text,text,text,text,text,text,text) to anon, authenticated;
