-- Domina OAB - Fase 2: banco de questões e reportes

create table if not exists public.disciplines (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  position integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.question_topics (
  id bigint generated by default as identity primary key,
  discipline_id bigint not null references public.disciplines(id) on delete cascade,
  name text not null,
  slug text not null,
  position integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(discipline_id,slug)
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discipline_id bigint not null references public.disciplines(id),
  topic_id bigint references public.question_topics(id) on delete set null,
  statement text not null,
  options jsonb not null,
  correct_index integer not null check (correct_index between 0 and 3),
  explanation text not null,
  source_label text,
  difficulty text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  status text not null default 'draft' check (status in ('draft','published','archived')),
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(options)='array' and jsonb_array_length(options)=4)
);

create index if not exists questions_discipline_status_idx on public.questions(discipline_id,status,position,id);
create index if not exists questions_topic_idx on public.questions(topic_id,status);

create table if not exists public.question_reports (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  reason text not null check (reason in ('gabarito','enunciado','explicacao','desatualizada','duplicada','outro')),
  message text,
  status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')),
  resolution_note text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists question_reports_status_created_idx on public.question_reports(status,created_at desc);
create index if not exists question_reports_question_idx on public.question_reports(question_id,status);

alter table public.disciplines enable row level security;
alter table public.question_topics enable row level security;
alter table public.questions enable row level security;
alter table public.question_reports enable row level security;

insert into public.disciplines(slug,name,position,active)
values ('etica-profissional','Ética Profissional',1,true)
on conflict(slug) do update set name=excluded.name,position=excluded.position,active=true,updated_at=now();

insert into public.question_topics(discipline_id,name,slug,position,active)
select d.id,x.name,x.slug,x.position,true
from public.disciplines d
cross join (values
  ('Princípios fundamentais','principios-fundamentais',1),
  ('Sigilo profissional','sigilo-profissional',2),
  ('Honorários advocatícios','honorarios-advocaticios',3)
) as x(name,slug,position)
where d.slug='etica-profissional'
on conflict(discipline_id,slug) do update set name=excluded.name,position=excluded.position,active=true,updated_at=now();

insert into public.questions(code,discipline_id,topic_id,statement,options,correct_index,explanation,source_label,difficulty,status,position)
select 'ETICA-DEMO-001',d.id,t.id,
  'No exercício profissional, qual conduta está alinhada ao papel social da advocacia?',
  '["Tratar a atividade exclusivamente como comércio","Atuar com independência, honestidade e compromisso com a Justiça","Subordinar a orientação jurídica à conveniência de terceiros","Priorizar a publicidade pessoal sobre o interesse do cliente"]'::jsonb,
  1,
  'A advocacia é função essencial à Justiça e deve ser exercida com independência, honestidade e observância da função social da profissão.',
  'Questão autoral demonstrativa','medium','published',1
from public.disciplines d join public.question_topics t on t.discipline_id=d.id and t.slug='principios-fundamentais'
where d.slug='etica-profissional'
on conflict(code) do nothing;

insert into public.questions(code,discipline_id,topic_id,statement,options,correct_index,explanation,source_label,difficulty,status,position)
select 'ETICA-DEMO-002',d.id,t.id,
  'O dever de sigilo profissional do advogado alcança informações recebidas em razão de sua atividade?',
  '["Não, quando ainda não existe processo judicial","Sim, inclusive informações recebidas em consulta, salvo hipóteses legalmente justificadas","Somente quando o cliente assina termo específico","Apenas informações presentes em autos sigilosos"]'::jsonb,
  1,
  'O sigilo alcança fatos conhecidos em razão do exercício profissional, inclusive durante consultas, ressalvadas as hipóteses justificadas pelo Código de Ética.',
  'Questão autoral demonstrativa','medium','published',2
from public.disciplines d join public.question_topics t on t.discipline_id=d.id and t.slug='sigilo-profissional'
where d.slug='etica-profissional'
on conflict(code) do nothing;

insert into public.questions(code,discipline_id,topic_id,statement,options,correct_index,explanation,source_label,difficulty,status,position)
select 'ETICA-DEMO-003',d.id,t.id,
  'Ao ajustar honorários, qual prática melhor preserva a transparência na relação com o cliente?',
  '["Definir apenas verbalmente para permitir alterações","Omitir despesas previsíveis até o final do serviço","Formalizar condições, valores e extensão do serviço contratado","Vincular todo pagamento obrigatoriamente ao êxito"]'::jsonb,
  2,
  'O contrato escrito delimita o serviço, a forma de pagamento, as despesas e as responsabilidades, reduzindo ambiguidades na relação profissional.',
  'Questão autoral demonstrativa','medium','published',3
from public.disciplines d join public.question_topics t on t.discipline_id=d.id and t.slug='honorarios-advocaticios'
where d.slug='etica-profissional'
on conflict(code) do nothing;

create or replace function public.public_questions(p_discipline_slug text)
returns jsonb
language sql
security definer
set search_path=public
as $$
  select coalesce(jsonb_agg(to_jsonb(x) order by x.position,x.id),'[]'::jsonb)
  from (
    select q.id,q.code,d.slug discipline_slug,d.name discipline,t.name topic,q.statement,q.options,q.difficulty,q.position
    from public.questions q
    join public.disciplines d on d.id=q.discipline_id
    left join public.question_topics t on t.id=q.topic_id
    where d.slug=p_discipline_slug and d.active=true and q.status='published'
    order by q.position,q.id
  ) x;
$$;

create or replace function public.verify_question(p_question_id bigint,p_option integer)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare q public.questions%rowtype;
begin
  select * into q from public.questions where id=p_question_id and status='published';
  if not found then raise exception 'question_not_found'; end if;
  if p_option < 0 or p_option > 3 then raise exception 'invalid_option'; end if;
  return jsonb_build_object('correct',p_option=q.correct_index,'correct_index',q.correct_index,'explanation',q.explanation);
end;
$$;

create or replace function public.report_question(p_question_id bigint,p_reason text,p_message text default null)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  if p_reason not in ('gabarito','enunciado','explicacao','desatualizada','duplicada','outro') then raise exception 'invalid_reason'; end if;
  if not exists(select 1 from public.questions where id=p_question_id and status='published') then raise exception 'question_not_found'; end if;
  insert into public.question_reports(question_id,user_id,reason,message)
  values(p_question_id,auth.uid(),p_reason,nullif(left(trim(coalesce(p_message,'')),1000),'')) returning id into v_id;
  return jsonb_build_object('ok',true,'report_id',v_id);
end;
$$;

create or replace function public.admin_questions(p_query text default null,p_status text default null)
returns jsonb
language sql
security definer
set search_path=public
as $$
  select coalesce(jsonb_agg(to_jsonb(x) order by x.updated_at desc),'[]'::jsonb)
  from (
    select q.id,q.code,d.slug discipline_slug,d.name discipline,t.id topic_id,t.name topic,q.statement,q.options,q.correct_index,q.explanation,q.source_label,q.difficulty,q.status,q.position,q.created_at,q.updated_at,
      (select count(*)::int from public.question_reports r where r.question_id=q.id and r.status in ('open','reviewing')) open_reports
    from public.questions q
    join public.disciplines d on d.id=q.discipline_id
    left join public.question_topics t on t.id=q.topic_id
    where (coalesce(trim(p_status),'')='' or q.status=p_status)
      and (coalesce(trim(p_query),'')='' or lower(q.code) like '%'||lower(trim(p_query))||'%' or lower(q.statement) like '%'||lower(trim(p_query))||'%' or lower(coalesce(t.name,'')) like '%'||lower(trim(p_query))||'%')
    order by q.updated_at desc
    limit 300
  ) x;
$$;

create or replace function public.admin_save_question(
  p_id bigint,
  p_code text,
  p_discipline_slug text,
  p_topic text,
  p_statement text,
  p_options jsonb,
  p_correct_index integer,
  p_explanation text,
  p_source_label text,
  p_difficulty text,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_discipline bigint; v_topic bigint; v_id bigint; v_topic_slug text;
begin
  if jsonb_typeof(p_options)<>'array' or jsonb_array_length(p_options)<>4 then raise exception 'four_options_required'; end if;
  if p_correct_index not between 0 and 3 then raise exception 'invalid_correct_index'; end if;
  if p_difficulty not in ('easy','medium','hard') then raise exception 'invalid_difficulty'; end if;
  if p_status not in ('draft','published','archived') then raise exception 'invalid_status'; end if;
  select id into v_discipline from public.disciplines where slug=p_discipline_slug;
  if v_discipline is null then raise exception 'discipline_not_found'; end if;
  v_topic_slug := lower(regexp_replace(trim(p_topic),'[^a-zA-Z0-9]+','-','g'));
  select id into v_topic from public.question_topics where discipline_id=v_discipline and lower(name)=lower(trim(p_topic)) limit 1;
  if v_topic is null then
    insert into public.question_topics(discipline_id,name,slug,position) values(v_discipline,trim(p_topic),v_topic_slug,999)
    on conflict(discipline_id,slug) do update set name=excluded.name,updated_at=now() returning id into v_topic;
  end if;
  if p_id is null then
    insert into public.questions(code,discipline_id,topic_id,statement,options,correct_index,explanation,source_label,difficulty,status,position)
    values(upper(trim(p_code)),v_discipline,v_topic,trim(p_statement),p_options,p_correct_index,trim(p_explanation),nullif(trim(p_source_label),''),p_difficulty,p_status,999)
    returning id into v_id;
  else
    update public.questions set code=upper(trim(p_code)),discipline_id=v_discipline,topic_id=v_topic,statement=trim(p_statement),options=p_options,correct_index=p_correct_index,explanation=trim(p_explanation),source_label=nullif(trim(p_source_label),''),difficulty=p_difficulty,status=p_status,updated_at=now()
    where id=p_id returning id into v_id;
    if v_id is null then raise exception 'question_not_found'; end if;
  end if;
  return jsonb_build_object('ok',true,'id',v_id);
end;
$$;

create or replace function public.admin_set_question_status(p_id bigint,p_status text)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if p_status not in ('draft','published','archived') then raise exception 'invalid_status'; end if;
  update public.questions set status=p_status,updated_at=now() where id=p_id;
  if not found then raise exception 'question_not_found'; end if;
end;
$$;

create or replace function public.admin_reports(p_status text default null)
returns jsonb
language sql
security definer
set search_path=public
as $$
  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
  from (
    select r.id,r.question_id,q.code,q.statement,d.name discipline,t.name topic,r.reason,r.message,r.status,r.resolution_note,r.created_at,r.resolved_at,
      coalesce(p.email,u.email) reporter_email
    from public.question_reports r
    join public.questions q on q.id=r.question_id
    join public.disciplines d on d.id=q.discipline_id
    left join public.question_topics t on t.id=q.topic_id
    left join public.user_profiles p on p.user_id=r.user_id
    left join auth.users u on u.id=r.user_id
    where coalesce(trim(p_status),'')='' or r.status=p_status
    order by r.created_at desc
    limit 300
  ) x;
$$;

create or replace function public.admin_resolve_report(p_id bigint,p_status text,p_note text default null)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if p_status not in ('reviewing','resolved','dismissed') then raise exception 'invalid_status'; end if;
  update public.question_reports
  set status=p_status,resolution_note=nullif(left(trim(coalesce(p_note,'')),1000),''),resolved_at=case when p_status in ('resolved','dismissed') then now() else null end,updated_at=now()
  where id=p_id;
  if not found then raise exception 'report_not_found'; end if;
end;
$$;

revoke all on function public.public_questions(text) from public;
revoke all on function public.verify_question(bigint,integer) from public;
revoke all on function public.report_question(bigint,text,text) from public;
revoke all on function public.admin_questions(text,text) from public,anon,authenticated;
revoke all on function public.admin_save_question(bigint,text,text,text,text,jsonb,integer,text,text,text,text) from public,anon,authenticated;
revoke all on function public.admin_set_question_status(bigint,text) from public,anon,authenticated;
revoke all on function public.admin_reports(text) from public,anon,authenticated;
revoke all on function public.admin_resolve_report(bigint,text,text) from public,anon,authenticated;

grant execute on function public.public_questions(text) to anon,authenticated;
grant execute on function public.verify_question(bigint,integer) to anon,authenticated;
grant execute on function public.report_question(bigint,text,text) to anon,authenticated;
grant execute on function public.admin_questions(text,text) to service_role;
grant execute on function public.admin_save_question(bigint,text,text,text,text,jsonb,integer,text,text,text,text) to service_role;
grant execute on function public.admin_set_question_status(bigint,text) to service_role;
grant execute on function public.admin_reports(text) to service_role;
grant execute on function public.admin_resolve_report(bigint,text,text) to service_role;
