do $$
declare r record;
begin
  for r in
    select id from public.questions
    where code in (
      'ETICA-L2-013','ETICA-L2-014','ETICA-L2-015','ETICA-L3-023','ETICA-L3-024','ETICA-L3-025','ETICA-L4-064','ETICA-L4-065',
      'ETICA-L2-016','ETICA-L2-017','ETICA-L3-026','ETICA-L3-027','ETICA-L3-028','ETICA-L4-066',
      'ETICA-L2-018','ETICA-L2-019','ETICA-L3-029','ETICA-L3-030','ETICA-L3-031','ETICA-L4-062','ETICA-L4-063'
    )
  loop
    perform public.snapshot_question_version(r.id,'legal_review_high_incidence_2026_09_04','system@dominaoab.com.br');
  end loop;
end $$;

-- DIREITOS E PRERROGATIVAS
update public.questions
set statement='Um advogado precisa ingressar em uma delegacia fora do horário de expediente para exercer atividade profissional. A autoridade afirma que o ingresso só seria possível durante o expediente e com a presença do delegado titular. À luz do Estatuto da Advocacia:',
    options='["a autoridade está correta em ambos os pontos","o advogado pode ingressar em delegacias e prisões mesmo fora da hora de expediente e independentemente da presença de seus titulares","o ingresso fora do expediente depende sempre de autorização judicial","a prerrogativa existe apenas quando o advogado apresenta procuração com poderes especiais"]'::jsonb,
    correct_index=1,
    explanation='O Estatuto assegura ao advogado ingressar livremente em delegacias e prisões mesmo fora da hora de expediente e independentemente da presença de seus titulares. Fundamento: Lei nº 8.906/1994, art. 7º, VI, b.',
    source_label='Autoral | EAOAB, art. 7º, VI, b',
    subtopic='Ingresso em delegacias e prisões', updated_at=now()
where code='ETICA-L2-013';

update public.questions set source_label='Autoral | EAOAB, art. 6º, caput', explanation='Não há hierarquia nem subordinação entre advogados, magistrados e membros do Ministério Público, devendo todos tratar-se com consideração e respeito recíprocos. Fundamento: Lei nº 8.906/1994, art. 6º, caput.', updated_at=now() where code='ETICA-L2-014';

update public.questions
set statement='Advogado comparece ao fórum e solicita falar diretamente com o magistrado em seu gabinete. A assessoria condiciona o atendimento a agendamento prévio para outro dia, embora o juiz esteja disponível. Segundo o Estatuto da Advocacia:',
    options='["o agendamento prévio é requisito legal obrigatório","o advogado pode dirigir-se diretamente ao magistrado em sala ou gabinete, independentemente de horário previamente marcado ou outra condição, observada a ordem de chegada","o contato direto somente é permitido em processo criminal","o atendimento depende de autorização da Presidência do Tribunal"]'::jsonb,
    correct_index=1,
    explanation='É direito do advogado dirigir-se diretamente aos magistrados nas salas e gabinetes de trabalho, independentemente de horário previamente marcado ou outra condição, observada a ordem de chegada. Fundamento: Lei nº 8.906/1994, art. 7º, VIII.', source_label='Autoral | EAOAB, art. 7º, VIII', subtopic='Acesso direto aos magistrados', updated_at=now()
where code='ETICA-L2-015';

update public.questions set explanation='O advogado pode examinar elementos já documentados em procedimento investigatório e obter cópias. Em autos sujeitos a sigilo, deve apresentar procuração; a autoridade pode delimitar o acesso a elementos relativos a diligências em andamento e ainda não documentados quando houver risco à eficácia da diligência. Fundamento: Lei nº 8.906/1994, art. 7º, XIV e §§ 10 e 11.', source_label='Autoral | EAOAB, art. 7º, XIV e §§10-11', updated_at=now() where code='ETICA-L3-023';
update public.questions set explanation='A inviolabilidade do escritório, local de trabalho, instrumentos, correspondência e comunicações profissionais é garantia funcional, mas não absoluta. Havendo indícios de autoria e materialidade de crime praticado por advogado, a quebra depende de decisão judicial motivada e mandado específico e pormenorizado, observadas as proteções legais aos materiais de clientes. Fundamento: Lei nº 8.906/1994, art. 7º, II e §§ 6º e 7º.', source_label='Autoral | EAOAB, art. 7º, II e §§6º-7º', updated_at=now() where code='ETICA-L3-024';
update public.questions set statement='Advogado regularmente inscrito é preso cautelarmente, antes do trânsito em julgado da condenação. Quanto ao local de custódia, assinale a alternativa correta.', explanation='O art. 7º, V, assegura ao advogado, antes do trânsito em julgado, recolhimento em sala de Estado-Maior com instalações e comodidades condignas e, na sua falta, prisão domiciliar. Na ADI 1.127, o STF preservou essa prerrogativa e afastou a expressão que submetia o reconhecimento da sala à OAB.', source_label='Autoral | EAOAB, art. 7º, V | STF, ADI 1.127', updated_at=now() where code='ETICA-L3-025';
update public.questions set options='["em qualquer crime, desde que a família seja comunicada","em caso de crime inafiançável, observado o inciso IV do art. 7º quanto à participação e comunicação da OAB","mediante autorização prévia do Conselho Seccional","nunca, pois goza de imunidade total à prisão"]'::jsonb, correct_index=1, explanation='Por motivo ligado ao exercício da profissão, o advogado somente pode ser preso em flagrante em caso de crime inafiançável, observado o art. 7º, IV. Esse inciso prevê a presença de representante da OAB na lavratura quando a prisão decorre do exercício profissional; o STF ressalvou, na ADI 1.127, que a ausência do representante não invalida a prisão se a OAB, regularmente comunicada, não o enviar em tempo hábil.', source_label='Autoral | EAOAB, art. 7º, IV e §3º | STF, ADI 1.127', updated_at=now() where code='ETICA-L4-064';
update public.questions set explanation='O advogado pode examinar, mesmo sem procuração, autos de processos findos ou em andamento não sujeitos a sigilo e obter cópias. Em procedimentos investigatórios, o art. 7º, XIV e §§ 10 e 11 disciplina o acesso, exigindo procuração em autos sigilosos e permitindo restrição apenas quanto a diligências em andamento e ainda não documentadas quando houver risco à sua eficácia.', source_label='Autoral | EAOAB, art. 7º, XIII-XIV e §§10-13', updated_at=now() where code='ETICA-L4-065';

-- HONORÁRIOS
update public.questions
set statement='Antes da expedição de mandado de levantamento ou precatório, o advogado junta aos autos o contrato de honorários. O cliente não demonstra pagamento prévio. Segundo o Estatuto, o juiz deve:',
    options='["ignorar o contrato e pagar integralmente ao cliente","determinar o pagamento direto ao advogado, por dedução da quantia a ser recebida pelo constituinte, na forma do contrato","exigir nova ação autônoma de cobrança em qualquer hipótese","converter obrigatoriamente os honorários contratuais em honorários de sucumbência"]'::jsonb, correct_index=1,
    explanation='Se o advogado juntar o contrato de honorários antes da expedição do mandado de levantamento ou precatório, o juiz deve determinar o pagamento direto ao profissional por dedução da quantia a ser recebida pelo constituinte, salvo se este provar que já os pagou. Fundamento: Lei nº 8.906/1994, art. 22, § 4º.', source_label='Autoral | EAOAB, art. 22, §4º', subtopic='Destaque e pagamento direto de honorários contratuais', updated_at=now()
where code='ETICA-L2-016';
update public.questions set source_label='Autoral | CED OAB, art. 48 e §1º', explanation='O Código de Ética estabelece que a prestação de serviços advocatícios será contratada preferentemente por escrito. O instrumento deve definir com clareza objeto, honorários, forma de pagamento, extensão do patrocínio e a hipótese de transação ou acordo. Fundamento: Código de Ética e Disciplina da OAB, art. 48 e § 1º.', updated_at=now() where code='ETICA-L2-017';
update public.questions set explanation='O Estatuto fixa prazo de cinco anos para a ação de cobrança de honorários advocatícios, contado do marco aplicável a cada hipótese legal, como vencimento do contrato, trânsito em julgado da decisão que os fixar, ultimação do serviço extrajudicial, desistência/transação ou renúncia/revogação do mandato. Fundamento: Lei nº 8.906/1994, art. 25.', source_label='Autoral | EAOAB, art. 25', updated_at=now() where code='ETICA-L3-026';
update public.questions set source_label='Autoral | EAOAB, art. 24, §4º', explanation='O acordo celebrado pelo cliente com a parte contrária, salvo aquiescência do advogado, não prejudica os honorários convencionados nem os concedidos por sentença. Fundamento: Lei nº 8.906/1994, art. 24, § 4º.', updated_at=now() where code='ETICA-L3-027';
update public.questions set statement='Advogado substabelecido com reserva de poderes possui contrato de honorários celebrado diretamente com o cliente. À luz da redação atual do Estatuto, ele:', options='["jamais pode cobrar honorários sem a intervenção do substabelecente","pode cobrar os honorários previstos em seu contrato com o cliente, pois essa hipótese constitui exceção à regra geral do substabelecimento com reserva","só pode cobrar após renunciar ao substabelecimento","depende obrigatoriamente de autorização judicial para cobrar"]'::jsonb, correct_index=1, explanation='A regra geral é que o advogado substabelecido com reserva de poderes não cobra honorários sem a intervenção daquele que lhe conferiu o substabelecimento. A redação atual do Estatuto excepciona a hipótese em que o substabelecido com reserva possui contrato celebrado com o cliente. Fundamento: Lei nº 8.906/1994, art. 26 e parágrafo único.', source_label='Autoral | EAOAB, art. 26 e parágrafo único', subtopic='Substabelecimento com reserva e contrato próprio', updated_at=now() where code='ETICA-L3-028';
update public.questions set explanation='Na hipótese de falecimento ou incapacidade civil do advogado, os honorários de sucumbência proporcionais ao trabalho realizado são recebidos por seus sucessores ou representantes legais. Fundamento: Lei nº 8.906/1994, art. 24, § 2º.', source_label='Autoral | EAOAB, art. 24, §2º', updated_at=now() where code='ETICA-L4-066';

-- INCOMPATIBILIDADES E IMPEDIMENTOS
update public.questions set statement='Professor de curso jurídico é servidor de universidade pública e pretende exercer advocacia contra a Fazenda Pública que o remunera. Considerando apenas o impedimento previsto no art. 30, I, do Estatuto:', options='["o impedimento aplica-se integralmente a todo docente servidor público","os docentes dos cursos jurídicos são expressamente excluídos dessa hipótese de impedimento","a docência gera incompatibilidade total com a advocacia","a atuação só seria possível em causa própria"]'::jsonb, correct_index=1, explanation='O art. 30, I, impede servidores da administração direta, indireta ou fundacional de advogar contra a Fazenda Pública que os remunera ou à qual se vincule a entidade empregadora. O parágrafo único exclui expressamente dessa hipótese os docentes dos cursos jurídicos.', source_label='Autoral | EAOAB, art. 30, I e parágrafo único', subtopic='Docente de curso jurídico e exceção ao impedimento', updated_at=now() where code='ETICA-L2-018';
update public.questions set statement='Pessoa ocupa cargo de direção em órgão da Administração Pública, mas suas atribuições não envolvem poder de decisão relevante sobre interesses de terceiros. À luz do art. 28 do Estatuto, assinale a correta.', options='["todo cargo denominado direção gera automaticamente incompatibilidade, sem qualquer ressalva","a hipótese do art. 28, III, pode ser afastada quando não houver poder de decisão relevante sobre interesses de terceiros, a juízo do Conselho competente da OAB","o cargo gera apenas impedimento contra a Fazenda Pública em qualquer situação","a análise da OAB é vedada porque somente o empregador define a compatibilidade"]'::jsonb, correct_index=1, explanation='Embora o art. 28, III, preveja incompatibilidade para cargos ou funções de direção na Administração, o § 2º exclui dessa hipótese quem não detenha poder de decisão relevante sobre interesses de terceiros, a juízo do Conselho competente da OAB, além da administração acadêmica diretamente ligada ao magistério jurídico.', source_label='Autoral | EAOAB, art. 28, III e §2º', subtopic='Cargo de direção sem poder decisório relevante', updated_at=now() where code='ETICA-L2-019';
update public.questions set explanation='O chefe do Poder Executivo está entre as hipóteses expressas de incompatibilidade com a advocacia, que produz proibição total do exercício profissional, inclusive em causa própria. O prefeito municipal exerce a chefia do Poder Executivo local. Fundamento: Lei nº 8.906/1994, arts. 27 e 28, I.', source_label='Autoral | EAOAB, arts. 27 e 28, I', updated_at=now() where code='ETICA-L3-029';
update public.questions set statement='Durante a investidura, um Procurador-Geral de ente público pretende exercer advocacia privada sem relação com suas atribuições institucionais. Segundo o Estatuto da Advocacia:', options='["a atuação privada é livre, desde que não seja contra o ente que o remunera","os Procuradores-Gerais, Advogados-Gerais, Defensores-Gerais e dirigentes de órgãos jurídicos públicos são exclusivamente legitimados para a advocacia vinculada à função durante a investidura","há apenas impedimento em causas tributárias","a restrição existe somente se o cargo for comissionado"]'::jsonb, correct_index=1, explanation='Durante a investidura, Procuradores-Gerais, Advogados-Gerais, Defensores-Gerais e dirigentes de órgãos jurídicos da Administração Pública direta, indireta e fundacional são exclusivamente legitimados para o exercício da advocacia vinculada à função que exercem. Fundamento: Lei nº 8.906/1994, art. 29.', source_label='Autoral | EAOAB, art. 29', subtopic='Dirigentes da advocacia pública e exclusividade funcional', updated_at=now() where code='ETICA-L3-030';
update public.questions set explanation='Cargos ou funções vinculados direta ou indiretamente a atividade policial de qualquer natureza são incompatíveis com a advocacia. Os §§ 3º e 4º inseridos em 2022, que pretendiam permitir atuação em causa própria a policiais e militares, foram declarados inconstitucionais pelo STF na ADI 7.227. Fundamento: Lei nº 8.906/1994, art. 28, V; STF, ADI 7.227.', source_label='Autoral | EAOAB, art. 28, V | STF, ADI 7.227', updated_at=now() where code='ETICA-L3-031';
update public.questions set source_label='Autoral | EAOAB, arts. 27 e 28, VIII', explanation='Funções de direção e gerência em instituições financeiras, inclusive privadas, são incompatíveis com a advocacia. A incompatibilidade importa proibição total do exercício profissional. Fundamentos: Lei nº 8.906/1994, arts. 27 e 28, VIII.', updated_at=now() where code='ETICA-L4-062';
update public.questions set source_label='Autoral | EAOAB, art. 30, II', explanation='Membros do Poder Legislativo, em seus diferentes níveis, sofrem impedimento parcial para advogar contra ou a favor das pessoas jurídicas e entidades enumeradas no art. 30, II. A incompatibilidade total do art. 28, I, alcança especificamente os membros da Mesa do Poder Legislativo e seus substitutos legais.', updated_at=now() where code='ETICA-L4-063';

update public.questions set status='published', updated_at=now()
where code in (
  'ETICA-L2-013','ETICA-L2-014','ETICA-L2-015','ETICA-L3-023','ETICA-L3-024','ETICA-L3-025','ETICA-L4-064','ETICA-L4-065',
  'ETICA-L2-016','ETICA-L2-017','ETICA-L3-026','ETICA-L3-027','ETICA-L3-028','ETICA-L4-066',
  'ETICA-L2-018','ETICA-L2-019','ETICA-L3-029','ETICA-L3-030','ETICA-L3-031','ETICA-L4-062','ETICA-L4-063'
);
