create table if not exists public.admin_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','administrator','editor','legal_reviewer','support')),
  active boolean not null default true,
  granted_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_members enable row level security;
revoke all on table public.admin_members from anon, authenticated;
grant select, insert, update, delete on table public.admin_members to service_role;

create index if not exists admin_members_role_active_idx on public.admin_members(role, active);

create or replace function public.touch_admin_member_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.touch_admin_member_updated_at() from public, anon, authenticated;
grant execute on function public.touch_admin_member_updated_at() to service_role;

drop trigger if exists admin_members_touch_updated_at on public.admin_members;
create trigger admin_members_touch_updated_at
before update on public.admin_members
for each row execute function public.touch_admin_member_updated_at();

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  actor_role text not null check (actor_role in ('owner','administrator','editor','legal_reviewer','support')),
  action text not null,
  resource_type text not null,
  resource_id text null,
  before_data jsonb null,
  after_data jsonb null,
  changed_fields text[] not null default '{}',
  request_id text null,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;
revoke all on table public.admin_audit_log from anon, authenticated;
grant select, insert on table public.admin_audit_log to service_role;
grant usage, select on sequence public.admin_audit_log_id_seq to service_role;

create index if not exists admin_audit_log_actor_created_idx on public.admin_audit_log(actor_user_id, created_at desc);
create index if not exists admin_audit_log_resource_created_idx on public.admin_audit_log(resource_type, resource_id, created_at desc);

insert into public.admin_members (user_id, role, active)
select u.id, 'owner', true
from auth.users u
where u.raw_app_meta_data->>'role' = 'admin'
on conflict (user_id) do update
set role = excluded.role,
    active = true,
    updated_at = now();

comment on table public.admin_members is 'Server-authorized administrative memberships and RBAC roles.';
comment on table public.admin_audit_log is 'Immutable application audit trail for administrative changes.';
