create table if not exists public.financial_adjustments (
  id bigint generated by default as identity primary key,
  payment_id bigint references public.payments(id) on delete set null,
  adjustment_type text not null check (adjustment_type in ('refund','reversal','chargeback','manual_adjustment')),
  amount_cents integer not null check (amount_cents <> 0),
  reason text not null check (length(trim(reason)) >= 3),
  actor_user_id uuid,
  actor_role text,
  created_at timestamptz not null default now()
);

alter table public.financial_adjustments enable row level security;
revoke all on table public.financial_adjustments from public, anon, authenticated;
grant all on table public.financial_adjustments to service_role;

create or replace function public.admin_record_financial_adjustment(
  p_payment_id bigint,
  p_adjustment_type text,
  p_amount_cents integer,
  p_reason text,
  p_actor_user_id uuid,
  p_actor_role text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_before jsonb;
  v_after jsonb;
begin
  if p_adjustment_type not in ('refund','reversal','chargeback','manual_adjustment') then
    raise exception 'Tipo de ajuste inválido';
  end if;
  if p_amount_cents = 0 then raise exception 'Valor não pode ser zero'; end if;
  if length(trim(coalesce(p_reason,''))) < 3 then raise exception 'Motivo obrigatório'; end if;
  if p_payment_id is not null then
    select to_jsonb(p) into v_before from public.payments p where p.id=p_payment_id;
    if v_before is null then raise exception 'Pagamento não encontrado'; end if;
  end if;

  insert into public.financial_adjustments(payment_id,adjustment_type,amount_cents,reason,actor_user_id,actor_role)
  values(p_payment_id,p_adjustment_type,p_amount_cents,trim(p_reason),p_actor_user_id,p_actor_role)
  returning id into v_id;

  select to_jsonb(a) into v_after from public.financial_adjustments a where a.id=v_id;
  insert into public.admin_audit_log(actor_user_id,actor_role,action,resource_type,resource_id,before_data,after_data,changed_fields)
  values(p_actor_user_id,p_actor_role,'financial_adjustment_created','financial_adjustment',v_id::text,v_before,v_after,array['adjustment_type','amount_cents','reason']);

  return jsonb_build_object('ok',true,'id',v_id);
end;
$$;

revoke all on function public.admin_record_financial_adjustment(bigint,text,integer,text,uuid,text) from public, anon, authenticated;
grant execute on function public.admin_record_financial_adjustment(bigint,text,integer,text,uuid,text) to service_role;

create or replace function public.admin_financial_reconciliation()
returns jsonb
language sql
security definer
set search_path = ''
as $$
  with pay as (
    select id, provider_payment_id, status from public.payments where provider_payment_id is not null
  ), evt as (
    select distinct on (resource_id) resource_id, event_type, processing_status, received_at
    from public.payment_events
    where resource_id is not null
    order by resource_id, received_at desc
  ), issues as (
    select 'payment_without_event'::text as kind, p.id::text as payment_id, p.provider_payment_id as external_id, p.status as payment_status, null::text as event_status
    from pay p left join evt e on e.resource_id=p.provider_payment_id where e.resource_id is null
    union all
    select 'event_without_payment', null::text, e.resource_id, null::text, e.processing_status
    from evt e left join pay p on p.provider_payment_id=e.resource_id where p.id is null
  )
  select jsonb_build_object(
    'totalPayments',(select count(*) from pay),
    'totalEvents',(select count(*) from evt),
    'issues',coalesce((select jsonb_agg(to_jsonb(i)) from issues i),'[]'::jsonb)
  );
$$;

revoke all on function public.admin_financial_reconciliation() from public, anon, authenticated;
grant execute on function public.admin_financial_reconciliation() to service_role;