-- Domina OAB - Fase 2: fluxo operacional dos reportes

alter table public.question_reports
  add column if not exists priority text not null default 'normal',
  add column if not exists assigned_to_email text,
  add column if not exists reviewed_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname='question_reports_priority_check'
  ) then
    alter table public.question_reports add constraint question_reports_priority_check
      check (priority in ('low','normal','high','critical'));
  end if;
end $$;

create table if not exists public.question_report_history (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.question_reports(id) on delete cascade,
  action text not null,
  from_status text,
  to_status text,
  priority text,
  assigned_to_email text,
  note text,
  actor_email text,
  created_at timestamptz not null default now()
);

create index if not exists question_report_history_report_idx
  on public.question_report_history(report_id,created_at desc);

alter table public.question_report_history enable row level security;
revoke all on table public.question_report_history from anon, authenticated;
grant select,insert on public.question_report_history to service_role;

create or replace function public.admin_reports(p_status text default null)
returns jsonb
language sql
security definer
set search_path=public
as $$
  select coalesce(jsonb_agg(to_jsonb(x) order by
    case x.priority when 'critical' then 1 when 'high' then 2 when 'normal' then 3 else 4 end,
    x.created_at desc
  ),'[]'::jsonb)
  from (
    select r.id,r.question_id,q.code,q.statement,d.name discipline,t.name topic,
      r.reason,r.message,r.status,r.priority,r.assigned_to_email,r.resolution_note,
      r.created_at,r.reviewed_at,r.resolved_at,
      coalesce(p.email,u.email) reporter_email,
      coalesce((select jsonb_agg(to_jsonb(h) order by h.created_at desc) from (
        select action,from_status,to_status,priority,assigned_to_email,note,actor_email,created_at
        from public.question_report_history
        where report_id=r.id
        order by created_at desc limit 20
      ) h),'[]'::jsonb) history
    from public.question_reports r
    join public.questions q on q.id=r.question_id
    join public.disciplines d on d.id=q.discipline_id
    left join public.question_topics t on t.id=q.topic_id
    left join public.user_profiles p on p.user_id=r.user_id
    left join auth.users u on u.id=r.user_id
    where coalesce(trim(p_status),'')='' or r.status=p_status
    order by r.created_at desc
    limit 300
  ) x;
$$;

create or replace function public.admin_update_report(
  p_id bigint,
  p_status text default null,
  p_note text default null,
  p_priority text default null,
  p_assigned_to_email text default null,
  p_actor_email text default null
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_old public.question_reports%rowtype;
  v_new_status text;
  v_new_priority text;
  v_new_assignee text;
begin
  select * into v_old from public.question_reports where id=p_id for update;
  if not found then raise exception 'report_not_found'; end if;

  v_new_status := coalesce(nullif(trim(p_status),''),v_old.status);
  v_new_priority := coalesce(nullif(trim(p_priority),''),v_old.priority);
  v_new_assignee := case
    when p_assigned_to_email is null then v_old.assigned_to_email
    when trim(p_assigned_to_email)='' then null
    else lower(trim(p_assigned_to_email))
  end;

  if v_new_status not in ('open','reviewing','resolved','dismissed') then raise exception 'invalid_status'; end if;
  if v_new_priority not in ('low','normal','high','critical') then raise exception 'invalid_priority'; end if;

  update public.question_reports set
    status=v_new_status,
    priority=v_new_priority,
    assigned_to_email=v_new_assignee,
    resolution_note=case when p_note is null then resolution_note else nullif(left(trim(p_note),1000),'') end,
    reviewed_at=case when v_new_status='reviewing' then coalesce(reviewed_at,now()) else reviewed_at end,
    resolved_at=case when v_new_status in ('resolved','dismissed') then coalesce(resolved_at,now()) else null end,
    updated_at=now()
  where id=p_id;

  insert into public.question_report_history(
    report_id,action,from_status,to_status,priority,assigned_to_email,note,actor_email
  ) values(
    p_id,
    case
      when v_old.status<>v_new_status then 'status_changed'
      when v_old.priority<>v_new_priority then 'priority_changed'
      when coalesce(v_old.assigned_to_email,'')<>coalesce(v_new_assignee,'') then 'assignment_changed'
      else 'note_updated'
    end,
    v_old.status,v_new_status,v_new_priority,v_new_assignee,
    nullif(left(trim(coalesce(p_note,'')),1000),''),
    lower(nullif(trim(coalesce(p_actor_email,'')),''))
  );
end;
$$;

revoke all on function public.admin_update_report(bigint,text,text,text,text,text) from public,anon,authenticated;
grant execute on function public.admin_update_report(bigint,text,text,text,text,text) to service_role;
