-- Domina OAB - Fase 2: catálogo e gestão de simulados

create table if not exists public.simulation_definitions (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text,
  discipline_id bigint references public.disciplines(id) on delete set null,
  topic_ids bigint[] not null default '{}',
  question_count integer not null check (question_count between 1 and 200),
  time_limit_minutes integer check (time_limit_minutes is null or time_limit_minutes between 1 and 600),
  randomize_questions boolean not null default true,
  randomize_options boolean not null default false,
  status text not null default 'draft' check (status in ('draft','published','paused','archived')),
  position integer not null default 0,
  created_by_email text,
  updated_by_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists simulation_definitions_status_idx
  on public.simulation_definitions(status,position,id);

alter table public.simulation_definitions enable row level security;
revoke all on table public.simulation_definitions from anon,authenticated;
grant select,insert,update,delete on public.simulation_definitions to service_role;

create or replace function public.admin_simulation_definitions()
returns jsonb
language sql
security definer
set search_path=public
as $$
  select coalesce(jsonb_agg(to_jsonb(x) order by x.position,x.id),'[]'::jsonb)
  from (
    select s.id,s.slug,s.name,s.description,s.discipline_id,d.slug discipline_slug,d.name discipline,
      s.topic_ids,s.question_count,s.time_limit_minutes,s.randomize_questions,s.randomize_options,
      s.status,s.position,s.created_by_email,s.updated_by_email,s.created_at,s.updated_at,
      (select count(*)::int from public.questions q
        where q.status='published'
          and (s.discipline_id is null or q.discipline_id=s.discipline_id)
          and (cardinality(s.topic_ids)=0 or q.topic_id=any(s.topic_ids))) available_questions
    from public.simulation_definitions s
    left join public.disciplines d on d.id=s.discipline_id
  ) x;
$$;

create or replace function public.admin_save_simulation_definition(
  p_id bigint,
  p_slug text,
  p_name text,
  p_description text,
  p_discipline_slug text,
  p_topic_ids bigint[],
  p_question_count integer,
  p_time_limit_minutes integer,
  p_randomize_questions boolean,
  p_randomize_options boolean,
  p_status text,
  p_actor_email text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_id bigint;
  v_discipline_id bigint;
  v_available integer;
begin
  if trim(coalesce(p_slug,''))='' or trim(coalesce(p_name,''))='' then raise exception 'required_fields_missing'; end if;
  if p_question_count < 1 or p_question_count > 200 then raise exception 'invalid_question_count'; end if;
  if p_time_limit_minutes is not null and (p_time_limit_minutes < 1 or p_time_limit_minutes > 600) then raise exception 'invalid_time_limit'; end if;
  if p_status not in ('draft','published','paused','archived') then raise exception 'invalid_status'; end if;

  if nullif(trim(coalesce(p_discipline_slug,'')),'') is not null then
    select id into v_discipline_id from public.disciplines where slug=trim(p_discipline_slug) and active=true;
    if v_discipline_id is null then raise exception 'discipline_not_found'; end if;
  end if;

  if p_status='published' then
    select count(*)::int into v_available
    from public.questions q
    where q.status='published'
      and (v_discipline_id is null or q.discipline_id=v_discipline_id)
      and (coalesce(cardinality(p_topic_ids),0)=0 or q.topic_id=any(p_topic_ids));
    if v_available < p_question_count then
      raise exception 'insufficient_published_questions:%/%',v_available,p_question_count;
    end if;
  end if;

  if p_id is null then
    insert into public.simulation_definitions(
      slug,name,description,discipline_id,topic_ids,question_count,time_limit_minutes,
      randomize_questions,randomize_options,status,created_by_email,updated_by_email
    ) values(
      lower(trim(p_slug)),trim(p_name),nullif(trim(coalesce(p_description,'')),''),v_discipline_id,
      coalesce(p_topic_ids,'{}'),p_question_count,p_time_limit_minutes,coalesce(p_randomize_questions,true),
      coalesce(p_randomize_options,false),p_status,lower(trim(p_actor_email)),lower(trim(p_actor_email))
    ) returning id into v_id;
  else
    update public.simulation_definitions set
      slug=lower(trim(p_slug)),name=trim(p_name),description=nullif(trim(coalesce(p_description,'')),''),
      discipline_id=v_discipline_id,topic_ids=coalesce(p_topic_ids,'{}'),question_count=p_question_count,
      time_limit_minutes=p_time_limit_minutes,randomize_questions=coalesce(p_randomize_questions,true),
      randomize_options=coalesce(p_randomize_options,false),status=p_status,
      updated_by_email=lower(trim(p_actor_email)),updated_at=now()
    where id=p_id returning id into v_id;
    if v_id is null then raise exception 'simulation_definition_not_found'; end if;
  end if;

  return jsonb_build_object('ok',true,'id',v_id);
end;
$$;

create or replace function public.admin_set_simulation_definition_status(
  p_id bigint,
  p_status text,
  p_actor_email text
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare s public.simulation_definitions%rowtype; v_available integer;
begin
  if p_status not in ('draft','published','paused','archived') then raise exception 'invalid_status'; end if;
  select * into s from public.simulation_definitions where id=p_id for update;
  if not found then raise exception 'simulation_definition_not_found'; end if;
  if p_status='published' then
    select count(*)::int into v_available from public.questions q
    where q.status='published'
      and (s.discipline_id is null or q.discipline_id=s.discipline_id)
      and (cardinality(s.topic_ids)=0 or q.topic_id=any(s.topic_ids));
    if v_available < s.question_count then raise exception 'insufficient_published_questions:%/%',v_available,s.question_count; end if;
  end if;
  update public.simulation_definitions set status=p_status,updated_by_email=lower(trim(p_actor_email)),updated_at=now() where id=p_id;
end;
$$;

create or replace function public.public_simulation_definition(p_slug text)
returns jsonb
language sql
security definer
set search_path=public
as $$
  select to_jsonb(x) from (
    select s.id,s.slug,s.name,s.description,d.slug discipline_slug,d.name discipline,
      s.topic_ids,s.question_count,s.time_limit_minutes,s.randomize_questions,s.randomize_options
    from public.simulation_definitions s
    left join public.disciplines d on d.id=s.discipline_id
    where s.slug=p_slug and s.status='published'
    limit 1
  ) x;
$$;

revoke all on function public.admin_simulation_definitions() from public,anon,authenticated;
revoke all on function public.admin_save_simulation_definition(bigint,text,text,text,text,bigint[],integer,integer,boolean,boolean,text,text) from public,anon,authenticated;
revoke all on function public.admin_set_simulation_definition_status(bigint,text,text) from public,anon,authenticated;
revoke all on function public.public_simulation_definition(text) from public;
grant execute on function public.admin_simulation_definitions() to service_role;
grant execute on function public.admin_save_simulation_definition(bigint,text,text,text,text,bigint[],integer,integer,boolean,boolean,text,text) to service_role;
grant execute on function public.admin_set_simulation_definition_status(bigint,text,text) to service_role;
grant execute on function public.public_simulation_definition(text) to anon,authenticated;
