-- Domina OAB - Fase 2: comunicações e preferências

create table if not exists public.communication_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  marketing_opt_in boolean not null default false,
  study_reminders boolean not null default false,
  transactional_enabled boolean not null default true,
  opt_in_source text,
  consent_version text,
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists communication_preferences_email_unique_idx
  on public.communication_preferences ((lower(email)));

create table if not exists public.communication_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  channel text not null default 'email' check (channel in ('email')),
  event_type text not null check (event_type in ('queued','sent','delivered','opened','clicked','bounced','failed','unsubscribed')),
  provider text not null default 'brevo',
  provider_message_id text,
  campaign_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists communication_events_user_created_idx on public.communication_events(user_id, created_at desc);
create index if not exists communication_events_campaign_idx on public.communication_events(campaign_key, created_at desc);

alter table public.communication_preferences enable row level security;
alter table public.communication_events enable row level security;

revoke all on table public.communication_preferences from anon, authenticated;
revoke all on table public.communication_events from anon, authenticated;

grant select,insert,update,delete on public.communication_preferences to service_role;
grant select,insert,update,delete on public.communication_events to service_role;

create or replace function public.admin_communications()
returns jsonb
language sql
security definer
set search_path = public
as $$
select jsonb_build_object(
  'totals', jsonb_build_object(
    'users',(select count(*)::int from public.communication_preferences),
    'marketingOptIn',(select count(*)::int from public.communication_preferences where marketing_opt_in),
    'studyReminders',(select count(*)::int from public.communication_preferences where study_reminders),
    'unsubscribed',(select count(*)::int from public.communication_preferences where unsubscribed_at is not null)
  ),
  'users', coalesce((select jsonb_agg(to_jsonb(x)) from (
    select p.user_id,p.email,p.marketing_opt_in,p.study_reminders,p.transactional_enabled,p.opt_in_source,p.consent_version,p.unsubscribed_at,p.updated_at,
      up.full_name,up.phone
    from public.communication_preferences p
    left join public.user_profiles up on up.user_id=p.user_id
    order by p.updated_at desc limit 200
  ) x),'[]'::jsonb),
  'events', coalesce((select jsonb_agg(to_jsonb(x)) from (
    select id,user_id,email,event_type,provider,campaign_key,created_at
    from public.communication_events
    order by created_at desc limit 50
  ) x),'[]'::jsonb)
);
$$;

revoke all on function public.admin_communications() from public,anon,authenticated;
grant execute on function public.admin_communications() to service_role;

create or replace function public.admin_set_communication_preferences(
  p_user_id uuid,
  p_marketing_opt_in boolean,
  p_study_reminders boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_email text;
begin
  select email into v_email from public.user_profiles where user_id=p_user_id;
  if v_email is null then raise exception 'user_not_found'; end if;
  insert into public.communication_preferences(user_id,email,marketing_opt_in,study_reminders,opt_in_source,consent_version,updated_at)
  values(p_user_id,v_email,p_marketing_opt_in,p_study_reminders,'admin','2026-09',now())
  on conflict(user_id) do update set
    email=excluded.email,
    marketing_opt_in=excluded.marketing_opt_in,
    study_reminders=excluded.study_reminders,
    unsubscribed_at=case when excluded.marketing_opt_in or excluded.study_reminders then null else public.communication_preferences.unsubscribed_at end,
    updated_at=now();
end;
$$;

revoke all on function public.admin_set_communication_preferences(uuid,boolean,boolean) from public,anon,authenticated;
grant execute on function public.admin_set_communication_preferences(uuid,boolean,boolean) to service_role;

insert into public.communication_preferences(user_id,email,marketing_opt_in,study_reminders,opt_in_source,consent_version)
select up.user_id,up.email,true,false,'founder-reservation','2026-09'
from public.user_profiles up
join public.pilot_leads pl on pl.user_id=up.user_id
where pl.activation_status='active'
on conflict(user_id) do nothing;
