with d as (
  select id from public.disciplines where slug='etica-profissional'
), topics as (
  select qt.id,qt.slug
  from public.question_topics qt
  join d on d.id=qt.discipline_id
  where qt.slug in ('advogado-empregado','responsabilidade-profissional')
), base as (
  select coalesce(max(position),0) max_position from public.questions
), items(code,topic_slug,statement,options,correct_index,explanation,source_label,difficulty,subtopic,incidence,ord) as (
  values
  ('ETICA-L5-069','advogado-empregado','A sociedade empresária Alfa contrata Joana como advogada empregada e determina que ela emita parecer jurídico favorável à empresa, apesar de entender tecnicamente que a tese é insustentável. À luz do Estatuto da Advocacia, assinale a afirmativa correta.', '["A relação de emprego retira a independência técnica da advogada","Joana deve seguir a orientação empresarial porque está subordinada hierarquicamente","A relação de emprego não retira a isenção técnica nem reduz a independência profissional da advogada","A independência técnica só existe se houver cláusula expressa no contrato de trabalho"]'::jsonb,2,'A relação de emprego, na qualidade de advogado, não retira a isenção técnica nem reduz a independência profissional inerentes à advocacia. Fundamento: Lei nº 8.906/1994, art. 18, caput.','Autoral | EAOAB, art. 18, caput','easy','Independência técnica do advogado empregado','low',1),
  ('ETICA-L5-070','advogado-empregado','Carlos é advogado empregado de uma empresa. O diretor pede que ele cuide gratuitamente de inventário particular da família do diretor, sem relação com o vínculo empregatício. Segundo o Estatuto:', '["Carlos é obrigado a aceitar porque é advogado empregado","Carlos só pode recusar se o pedido ocorrer fora do horário de trabalho","Carlos não está obrigado a prestar serviços profissionais de interesse pessoal do empregador fora da relação de emprego","Carlos é obrigado a aceitar, mas pode cobrar honorários adicionais"]'::jsonb,2,'O advogado empregado não está obrigado à prestação de serviços profissionais de interesse pessoal dos empregadores fora da relação de emprego. Fundamento: Lei nº 8.906/1994, art. 18, §1º.','Autoral | EAOAB, art. 18, §1º','easy','Serviços pessoais do empregador','low',2),
  ('ETICA-L5-071','advogado-empregado','Uma empresa pretende alterar o regime de trabalho de sua advogada empregada de presencial para misto durante a vigência do contrato. À luz da redação atual do Estatuto, essa alteração:', '["é proibida após a admissão","só pode ocorrer por convenção coletiva","pode ser pactuada por acordo individual simples entre as partes","depende de autorização prévia da OAB"]'::jsonb,2,'Durante a relação de emprego, as partes podem pactuar, por acordo individual simples, a alteração entre os regimes presencial, não presencial e misto. Fundamento: Lei nº 8.906/1994, art. 18, §§2º e 3º.','Autoral | EAOAB, art. 18, §§2º-3º','medium','Regimes presencial, remoto e misto','low',3),
  ('ETICA-L5-072','advogado-empregado','Advogada empregada de uma empresa trabalha nove horas em determinado dia. Considerando a regra geral do Estatuto aplicável ao advogado empregado que presta serviço para empresas, a hora excedente:', '["não gera adicional porque a jornada pode chegar a dez horas","deve ser remunerada com adicional não inferior a 100% sobre a hora normal","gera apenas adicional de 50%","só é remunerada se houver previsão no contrato escrito"]'::jsonb,1,'A jornada do advogado empregado que presta serviço para empresas não pode exceder oito horas contínuas e quarenta horas semanais. As horas excedentes são remuneradas com adicional não inferior a 100% sobre a hora normal, mesmo havendo contrato escrito. Fundamento: Lei nº 8.906/1994, art. 20, caput e §2º.','Autoral | EAOAB, art. 20, caput e §2º','medium','Jornada e horas extras','low',4),
  ('ETICA-L5-073','advogado-empregado','Em ação na qual a própria empresa empregadora é parte, são fixados honorários de sucumbência. Segundo o Estatuto da Advocacia, esses honorários:', '["pertencem exclusivamente à empresa empregadora","são devidos aos advogados empregados","pertencem ao cliente da empresa, e não ao advogado","somente pertencem ao advogado se o contrato de trabalho prever expressamente"]'::jsonb,1,'Nas causas em que for parte o empregador, ou pessoa por ele representada, os honorários de sucumbência são devidos aos advogados empregados. Fundamento: Lei nº 8.906/1994, art. 21.','Autoral | EAOAB, art. 21','medium','Honorários de sucumbência do advogado empregado','low',5),
  ('ETICA-L5-074','responsabilidade-profissional','Advogado perde prazo recursal por negligência e causa prejuízo comprovado ao cliente. À luz do Estatuto da Advocacia, a responsabilidade profissional do advogado:', '["somente existe se houver dolo","alcança atos praticados com dolo ou culpa no exercício profissional","é sempre objetiva, independentemente de culpa","é excluída quando o advogado atua por procuração"]'::jsonb,1,'O advogado é responsável pelos atos que, no exercício profissional, praticar com dolo ou culpa. Fundamento: Lei nº 8.906/1994, art. 32, caput.','Autoral | EAOAB, art. 32, caput','easy','Responsabilidade por dolo ou culpa','low',6),
  ('ETICA-L5-075','responsabilidade-profissional','Cliente e advogado combinam ajuizar demanda sabidamente infundada com documentos artificiosos para causar prejuízo à parte contrária. Em relação à responsabilidade do advogado por lide temerária:', '["o advogado jamais responde solidariamente com o cliente","a solidariedade é automática sempre que a ação for julgada improcedente","o advogado pode responder solidariamente com o cliente se estiver coligado com ele para lesar a parte contrária, mediante apuração em ação própria","a responsabilidade solidária depende apenas de decisão disciplinar da OAB"]'::jsonb,2,'Em caso de lide temerária, o advogado será solidariamente responsável com o cliente quando estiver coligado com ele para lesar a parte contrária, e essa circunstância deve ser apurada em ação própria. Fundamento: Lei nº 8.906/1994, art. 32, parágrafo único.','Autoral | EAOAB, art. 32, parágrafo único','medium','Lide temerária e responsabilidade solidária','low',7),
  ('ETICA-L5-076','responsabilidade-profissional','Um cliente, sem conhecimento do advogado, insiste em tese abusiva e pratica ato destinado a prejudicar a parte contrária. Apenas por esse fato, a responsabilidade solidária do advogado por lide temerária:', '["surge automaticamente porque o advogado representa o cliente","não é automática; exige coligação entre advogado e cliente para lesar a parte contrária e apuração em ação própria","depende apenas da derrota no processo","decorre de qualquer erro de estratégia processual"]'::jsonb,1,'A solidariedade prevista para lide temerária não nasce da simples representação processual nem da conduta isolada do cliente. Exige coligação entre advogado e cliente para lesar a parte contrária e apuração em ação própria. Fundamento: Lei nº 8.906/1994, art. 32, parágrafo único.','Autoral | EAOAB, art. 32, parágrafo único','hard','Requisitos da solidariedade por lide temerária','low',8),
  ('ETICA-L5-077','responsabilidade-profissional','Sócio de sociedade de advogados causa dano a cliente por omissão no exercício profissional. Quanto à responsabilidade patrimonial, assinale a correta.', '["apenas a sociedade responde, nunca o sócio","além da sociedade, o sócio responde subsidiária e ilimitadamente pelos danos causados aos clientes por ação ou omissão no exercício da advocacia","o sócio responde apenas até o valor de sua participação societária","a responsabilidade patrimonial exclui eventual responsabilidade disciplinar"]'::jsonb,1,'Além da sociedade, o sócio responde subsidiária e ilimitadamente pelos danos causados aos clientes por ação ou omissão no exercício da advocacia, sem prejuízo da responsabilidade disciplinar. Fundamento: Lei nº 8.906/1994, art. 17.','Autoral | EAOAB, art. 17','medium','Responsabilidade do sócio por danos ao cliente','low',9),
  ('ETICA-L5-078','responsabilidade-profissional','A aplicação de responsabilidade civil ao advogado por dano causado ao cliente impede, por si só, a apuração disciplinar do mesmo fato pela OAB?', '["Sim, porque haveria dupla punição pelo mesmo fato","Sim, salvo se houver condenação criminal","Não. A responsabilidade patrimonial pode coexistir com a responsabilidade disciplinar, conforme a hipótese","Não, mas somente quando houver sociedade de advogados"]'::jsonb,2,'O regime do Estatuto admite coexistência entre responsabilidade patrimonial e disciplinar. O art. 17 expressamente preserva a responsabilidade disciplinar do sócio, e o art. 32 disciplina a responsabilidade pelos atos profissionais com dolo ou culpa.','Autoral | EAOAB, arts. 17 e 32','medium','Responsabilidade civil e disciplinar','low',10)
), rows_to_insert as (
  select i.*,t.id topic_id,d.id discipline_id,b.max_position+i.ord position
  from items i
  join topics t on t.slug=i.topic_slug
  cross join d
  cross join base b
)
insert into public.questions(code,discipline_id,topic_id,statement,options,correct_index,explanation,source_label,difficulty,status,position,last_edited_by_email,subtopic,incidence)
select code,discipline_id,topic_id,statement,options,correct_index,explanation,source_label,difficulty,'published',position,'system@dominaoab.com.br',subtopic,incidence
from rows_to_insert
on conflict (code) do update set topic_id=excluded.topic_id,statement=excluded.statement,options=excluded.options,correct_index=excluded.correct_index,explanation=excluded.explanation,source_label=excluded.source_label,difficulty=excluded.difficulty,status='published',subtopic=excluded.subtopic,incidence=excluded.incidence,updated_at=now(),last_edited_by_email='system@dominaoab.com.br';

update public.question_topics qt
set active=true,updated_at=now()
from public.disciplines d
where qt.discipline_id=d.id
  and d.slug='etica-profissional'
  and qt.slug in ('advogado-empregado','responsabilidade-profissional');